steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME:latest
      - -f
      - Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME:latest
  - name: gcr.io/cloud-builders/gcloud
    args:
      #- --project=$_CLUSTER_PROJECT
      - --project=test1-227715
      - container
      - clusters
      - get-credentials
      - --zone=asia-east2-a
      - standard-cluster-1
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/webserver
      - webserver=gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-east2-a
      - CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1